### ISSUE TITLE
Hebrew Update - An inquiry before release

### ISSUE THREAD

**Issue by TheGamerKing777** [helloyanis/rucoy-calculator#24]
Hello,
I have just noticed there is something highlighted in the code of the file I have recently translated.
It's in Line 86, specifically with the symbol: '**&**'

I want it to match like it is said in Line 3 (same as in the application) - `אימון &amp; נזק`
However, since there are slashes in the beginning and end of this text in Line 86 - `\"אימון & נזק\`, I am not entirely sure how it should be written.

That's the reason I opened an issue, rather than to guess which type is correct.
Furthermore, I would be delighted to know;
1. What is the purpose of `amp&;`?
2. If an edit took place in Line 86, why it is changed to what you have wrote in the end?

Looking forward to your reply,
Hopefully to know a little better about this language.

**Comment by helloyanis** [comment]
Hi! To answer your question :
- Text in the XML format needs to be in `"quotation marks"`. It can work without, but I find there's better formatting when you put it in quotation marks.
- For that reason, when you want to put quotation marks that will display in the app and are not counted as formatting, you need to use `\"backslashes\" before quotation marks.`
- And `&amp;` is how you format the text to display the `&` character.
I will fix it for you, no worries!
